# Site settings
title: drain.tips
email: bottom@drain.tips
description: A Practical Recommendation Engine For the Specific Problem of Dealing With Drain Problems
twitter_username: draintips
github_username:  draintips

# Build settings
markdown: kramdown
